export const ADD_ERROR = 'ADD_ERROR';
export const REMOVE_ERROR = 'REMOVE_ERROR';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const CREATING_WASCHSTRASSE_FLAG = 'CREATING_WASCHSTRASSE_FLAG';
